version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: narwanto-portfolio
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
